# Specify the folder where Yarn should store its cache files
cacheFolder: .yarn

# Define the method Yarn should use to link node modules
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.5.0.cjs
